name: Akshay S Dinesh
shortname: ASD
markdown: kramdown
permalink: :title/
url: https://asd.learnlearn.in
paginate: 7
paginate_path: "/archive/:num/"
redcarpet:
    extensions: ["autolink", "footnotes", "strikethrough", "with_toc_data"]
jekyll-archives:
  enabled:
    - tags
  layout: "archive"
scripts: ["jquery-2.1.4.min", "mousetrap.min", "main"]
plugins:
  - jekyll-paginate
  - jekyll-archives
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"