name: Akshay S Dinesh
shortname: ASD
markdown: redcarpet
highlighter: pygments
permalink: :title/
url: http://asd.learnlearn.in
paginate: 5
paginate_path: "/archive/:num/"
redcarpet:
    extensions: ["autolink", "strikethrough"]
