name: Akshay S Dinesh
shortname: ASD
markdown: kramdown
permalink: :title/
url: https://asd.learnlearn.in
include: [".well-known"]
jekyll-archives:
  enabled:
    - tags
  layout: "archive"
plugins:
  - jekyll-archives
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"