name: Akshay S Dinesh
shortname: ASD
markdown: kramdown
permalink: :title/
url: https://asd.learnlearn.in
paginate: 5
paginate_path: "/archive/:num/"
redcarpet:
    extensions: ["autolink", "footnotes", "strikethrough", "with_toc_data"]
jekyll-archives:
  enabled:
    - tags
  layout: "archive"
scripts: ["jquery-2.1.4.min", "mousetrap.min", "main"]
gems:
  - jekyll-paginate
  - jekyll-archives
