name: Akshay S Dinesh
shortname: ASD
markdown: redcarpet
highlighter: pygments
permalink: :title/
url: http://asd.learnlearn.in
paginate: 5
paginate_path: "/archive/:num/"
redcarpet:
    extensions: ["autolink", "footnotes", "strikethrough", "with_toc_data"]
scripts: ["jquery-2.1.4.min", "mousetrap.min", "main"]
gems: [jekyll-paginate]