baseURL = 'https://asd.learnlearn.in'
languageCode = 'en-us'
title = 'ASD'

theme = 'asd'

[params]
feedSections = ["post"]
  [author]
    name = "Akshay S Dinesh"
    email = "asdofindia@gmail.com"

[taxonomies]
  tag = 'tags'

[permalinks]
  tags = "/tag/:slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'catppuccin-latte'

[outputs]
  home = ["HTML", "ATOM", "rss", "json"]
  page = ["HTML", "json"]
