[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  [params.theme_config]
    appearance        = "auto"
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true

# https://github.com/kaushalmodi/hugo-atom-feed
[mediaTypes."application/atom+xml"]
  suffixes = ["atom", "xml"]
[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "feed" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false